#!/bin/bash
# Extract build metadata from src/Makefile.in for use with build.zig
# This script parses the Makefile.in to extract source file lists

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOP_DIR="$(dirname "$SCRIPT_DIR")"
SRC_DIR="$TOP_DIR/src"

cd "$TOP_DIR"

echo "Extracting build metadata from src/Makefile.in..."

# Extract base_obj files (line 450-469), converting .o to .c
# Filter out GUI-specific files (X11, Cocoa, Windows, GTK)
# Add TUI-specific files that are normally added via configure variables
extract_base_sources() {
    # Extract the multi-line base_obj definition
    awk '/^base_obj = / {p=1} p {print} /^$/ {if(p) exit}' "$SRC_DIR/Makefile.in" | \
        sed 's/base_obj = //; s/ \\$//; s/\.o/.c/g; s/$(XMENU_OBJ)//g; s/$(XOBJ)//g; s/$(GTK_OBJ)//g; s/$(DBUS_OBJ)//g; s/$(CM_OBJ)/cm.c/g; s/$(MODULES_OBJ)//g; s/$(DYNLIB_OBJ)//g; s/$(NOTIFY_OBJ)//g; s/$(XWIDGETS_OBJ)//g; s/$(MSDOS_OBJ)//g; s/$(MSDOS_X_OBJ)//g; s/$(NS_OBJ)//g; s/$(CYGWIN_OBJ)//g; s/$(FONT_OBJ)//g; s/$(W32_OBJ)//g; s/$(WINDOW_SYSTEM_OBJ)//g; s/$(XGSELOBJ)//g; s/$(HAIKU_OBJ)//g; s/$(PGTK_OBJ)//g; s/$(ANDROID_OBJ)//g' | \
        tr ' ' '\n' | \
        grep -v "^$" | \
        grep -v "^\\$" | \
        sort -u
}

# Extract libgnu C files
extract_libgnu_sources() {
    # Get C source files from lib directory that are commonly needed
    # Include all needed utility files for TUI build
    find lib -name "*.c" -type f | \
        grep -E "(acl|alloca|binary-io|boot-time|byteswap|c-ctype|c-str|canonicalize|careadlinkat|chmodat|cloexec|close-stream|copy-file-range|dirent|dirfd|dtoastr|dtotimespec|dup2|fallocat|fchmodat|fd-open|filemode|filename|filevercmp|flexmember|fpending|fingerprint|futimens|free|fsusage|gen_tempname|get-permissions|getdelim|getrandom|getline|getprogname|hard-locale|isset|issymlink|lstat|malloc|md5|memchr|memcmp|memmem|memset_explicit|memmove|memcpy|memrchr|mkdir|mkancesdirs|mkostemp|mktime|nanosleep|nproc|nstrftime|openat-die|openat|pathmax|pending|pipe2|pthread|qcopy-acl|quotearl|read|realloc|same|save-cwd|set-permissions|sha|sig2str|sigdescr_np|streq|stat|stdbit|stdc|strchr|strcmp|strchrnul|strcpy|strerror|strlen|string|strncase|strndup|strnlen|strncmp|strto|tempname|time|timespec|u64|unsetenv|utimens|waitpid|wctype|xmalloc)" | \
        grep -v -E "(regex|strtoimax|strtoumax|printf|strftime|at-func|dynarray-skeleton|ialloca|malloc/dynarray|pthread_sigmask)" | \
        sort
}

# Generate base_sources.zig
generate_base_sources() {
    echo "// Auto-generated by build-aux/extract-metadata.sh"
    echo "// Source files for base_obj (TUI-only, no GUI)"
    echo ""
    echo "pub const base_sources = [_][]const u8{"
    extract_base_sources | while read -r file; do
        if [ -f "$SRC_DIR/${file#.c/}" ] || [ -f "$SRC_DIR/${file#src/}" ] || [ -f "$file" ]; then
            # Normalize path
            normalized_file="${file#src/}"
            if [ -f "$SRC_DIR/$normalized_file" ]; then
                echo "    \"src/$normalized_file\","
            fi
        fi
    done

    # Add TUI-specific files that are always needed
    # These are typically added by configure via TERMCAP_OBJ and other variables
    # Add TUI-specific files that are always needed
    # Note: kqueue.c is NOT added here - it's BSD/macOS-specific (HAVE_KQUEUE)
    # and should be conditionally compiled based on platform
    for extra_file in termcap.c tparam.c; do
        if [ -f "$SRC_DIR/$extra_file" ]; then
            echo "    \"src/$extra_file\","
        fi
    done

    echo "};"
}

# Generate libgnu_sources.zig
generate_libgnu_sources() {
    echo "// Auto-generated by build-aux/extract-metadata.sh"
    echo "// Gnulib compatibility library sources"
    echo ""
    echo "pub const libgnu_sources = [_][]const u8{"
    extract_libgnu_sources | while read -r file; do
        if [ -f "$file" ]; then
            echo "    \"$file\","
        fi
    done

    # Add nstrftime.c explicitly (needed by timefns.c)
    if [ -f "lib/nstrftime.c" ]; then
        echo "    \"lib/nstrftime.c\","
    fi

    echo "};"
}

# Generate platform-specific sources
generate_platform_sources() {
    echo "// Auto-generated by build-aux/extract-metadata.sh"
    echo "// Platform-specific sources (excluded from TUI builds)"
    echo ""
    echo "pub const gui_excluded_sources = [_][]const u8{"
    echo "    // X11"
    echo "    \"src/xterm.c\","
    echo "    \"src/xfns.c\","
    echo "    \"src/xmenu.c\","
    echo "    \"src/xselect.c\","
    echo "    \"src/xrdb.c\","
    echo "    \"src/xsmfns.c\","
    echo "    \"src/fringe.c\","
    echo "    \"src/image.c\","
    echo "    \"src/fontset.c\","
    echo "    \"src/dbusbind.c\","
    echo "    // macOS/Cocoa"
    echo "    \"src/nsterm.m\","
    echo "    \"src/nsfns.m\","
    echo "    \"src/nsmenu.m\","
    echo "    \"src/nsselect.m\","
    echo "    \"src/nsimage.m\","
    echo "    \"src/nsfont.m\","
    echo "    \"src/macfont.m\","
    echo "    \"src/nsxwidget.m\","
    echo "    // Windows"
    echo "    \"src/w32.c\","
    echo "    \"src/w32console.c\","
    echo "    \"src/w32cygwinx.c\","
    echo "    \"src/w32fns.c\","
    echo "    \"src/w32heap.c\","
    echo "    \"src/w32inevt.c\","
    echo "    \"src/w32notify.c\","
    echo "    \"src/w32menu.c\","
    echo "    \"src/w32proc.c\","
    echo "    \"src/w32reg.c\","
    echo "    \"src/w32select.c\","
    echo "    \"src/w32term.c\","
    echo "    \"src/w32xfns.c\","
    echo "    \"src/w16select.c\","
    echo "    \"src/widget.c\","
    echo "    // GTK"
    echo "    \"src/gtkutil.c\","
    echo "    \"src/xsettings.c\","
    echo "    \"src/xgselect.c\","
    echo "    \"src/ftfont.c\","
    echo "    \"src/xftfont.c\","
    echo "    \"src/hbfont.c\","
    echo "    // Haiku"
    echo "    \"src/haikuterm.c\","
    echo "    \"src/haikufns.c\","
    echo "    \"src/haikumenu.c\","
    echo "    \"src/haikufont.c\","
    echo "    // Android"
    echo "    \"src/androidterm.c\","
    echo "    \"src/androidfns.c\","
    echo "    \"src/androidfont.c\","
    echo "    \"src/androidselect.c\","
    echo "    \"src/androidvfs.c\","
    echo "    \"src/sfntfont-android.c\","
    echo "    // DOS"
    echo "    \"src/dosfns.c\","
    echo "    \"src/msdos.c\","
    echo "};"
}

# Create output directory
mkdir -p build-config

# Generate source files
echo "Generating build-config/base_sources.zig..."
generate_base_sources > build-config/base_sources.zig

echo "Generating build-config/libgnu_sources.zig..."
generate_libgnu_sources > build-config/libgnu_sources.zig

echo "Generating build-config/platform_sources.zig..."
generate_platform_sources > build-config/platform_sources.zig

# Count files
base_count=$(extract_base_sources | wc -l | tr -d ' ')
libgnu_count=$(extract_libgnu_sources | wc -l | tr -d ' ')

echo ""
echo "Metadata extraction complete:"
echo "  - Base sources: $base_count files"
echo "  - Libgnu sources: $libgnu_count files"
echo "  - Platform sources: excluded (GUI-only)"
echo ""
echo "Generated files:"
echo "  - build-config/base_sources.zig"
echo "  - build-config/libgnu_sources.zig"
echo "  - build-config/platform_sources.zig"
