//! Generates the ABI header and a non-normative ABI summary.  Outputs are
//! build artifacts outside tracked inherited Emacs C source.  The authoritative
//! ownership manifest is `src/proto-ui/adapter.zig`.

const std = @import("std");

const header =
    \\/* Generated by zig build; do not edit. */
    \\#ifndef PROTO_UI_ABI_V1_H
    \\#define PROTO_UI_ABI_V1_H
    \\
    \\#include <stddef.h>
    \\#include <stdint.h>
    \\
    \\#ifdef __cplusplus
    \\extern "C" {
    \\#endif
    \\
    \\#define PROTO_UI_ABI_VERSION 1u
    \\#define PROTO_UI_EUP_MAJOR 1u
    \\#define PROTO_UI_EUP_MINOR 0u
    \\#define PROTO_UI_HOST_V1_SIZE sizeof(ProtoUiHostV1)
    \\
    \\#if defined(_WIN32)
    \\#define PROTO_UI_API __declspec(dllexport)
    \\#elif defined(__GNUC__) || defined(__clang__)
    \\#define PROTO_UI_API __attribute__((visibility("default")))
    \\#else
    \\#define PROTO_UI_API
    \\#endif
    \\
    \\#define PROTO_UI_STATUS_SUCCESS 0u
    \\#define PROTO_UI_STATUS_INVALID_ARGUMENT 1u
    \\#define PROTO_UI_STATUS_ABI_MISMATCH 2u
    \\#define PROTO_UI_STATUS_CALLBACK_MISSING 3u
    \\#define PROTO_UI_STATUS_CALLBACK_FAILED 4u
    \\#define PROTO_UI_STATUS_FRAME_STATE_UNSUPPORTED 5u
    \\
    \\#define PROTO_UI_FRAME_STATE_HIDDEN 0u
    \\#define PROTO_UI_FRAME_STATE_VISIBLE 1u
    \\#define PROTO_UI_FRAME_STATE_ICONIFIED 2u
    \\
    \\typedef struct ProtoUiGeometry {
    \\  int32_t x;
    \\  int32_t y;
    \\  int32_t width;
    \\  int32_t height;
    \\} ProtoUiGeometry;
    \\
    \\typedef struct ProtoUiFrameState {
    \\  uint64_t generation;
    \\  uint8_t visibility;
    \\  uint8_t focused;
    \\  uint8_t reserved[6];
    \\} ProtoUiFrameState;
    \\
    \\typedef struct ProtoUiHostV1 {
    \\  uint32_t abi_version;
    \\  size_t size;
    \\  void *context;
    \\  uint64_t (*read_generation)(void *context, uint64_t object_id);
    \\  uint8_t (*read_geometry)(void *context, uint64_t object_id,
    \\                           ProtoUiGeometry *geometry);
    \\  uint8_t (*read_frame_state)(void *context, uint64_t frame_id,
    \\                              ProtoUiFrameState *frame_state);
    \\} ProtoUiHostV1;
    \\
    \\PROTO_UI_API uint8_t proto_ui_shim_abi_version(void);
    \\PROTO_UI_API uint8_t proto_ui_shim_host_validate(
    \\    const ProtoUiHostV1 *host);
    \\PROTO_UI_API uint8_t proto_ui_shim_read_generation(
    \\    const ProtoUiHostV1 *host, uint64_t object_id,
    \\    uint64_t *generation);
    \\PROTO_UI_API uint8_t proto_ui_shim_read_geometry(
    \\    const ProtoUiHostV1 *host, uint64_t object_id,
    \\    ProtoUiGeometry *geometry);
    \\PROTO_UI_API uint8_t proto_ui_shim_read_frame_state(
    \\    const ProtoUiHostV1 *host, uint64_t frame_id,
    \\    ProtoUiFrameState *frame_state);
    \\
    \\#ifdef __cplusplus
    \\}
    \\#endif
    \\
    \\#endif /* PROTO_UI_ABI_V1_H */
    \\
;

pub const manifest =
    \\{
    \\  "abi_version": 1,
    \\  "manifest_kind": "abi-summary-non-normative",
    \\  "authoritative_manifest": "src/proto-ui/adapter.zig",
    \\  "eup_major": 1,
    \\  "eup_minor": 0,
    \\  "boundary": "adapter-first",
    \\  "tables": {
    \\    "host_v1": {
    \\      "owner": "emacs-host",
    \\      "callbacks": ["read_generation", "read_geometry", "read_frame_state"],
    \\      "optional_callbacks": ["read_frame_state"]
    \\    },
    \\    "adapter_v1": {
    \\      "owner": "proto-ui-adapter",
    \\      "callbacks": ["capture_begin", "capture_window", "capture_row", "capture_cursor", "capture_damage", "capture_flush", "capture_cancel"]
    \\    }
    \\  },
    \\  "ownership": {
    \\    "emacs": ["buffers", "frames", "windows", "faces", "fonts", "redisplay"],
    \\    "adapter": ["eup_encoding", "session_state", "damage_policy", "transport"],
    \\    "frontend": ["scene", "input_capture", "renderer", "presentation"]
    \\  }
    \\}
    \\
;

const shim =
    \\/* Generated by zig build; do not edit. */
    \\#include "abi_v1.h"
    \\
    \\#define PROTO_UI_HOST_V1_LEGACY_SIZE offsetof(ProtoUiHostV1, read_frame_state)
    \\
    \\static uint8_t proto_ui_host_validate_v1(const ProtoUiHostV1 *host) {
    \\  if (host == NULL) return PROTO_UI_STATUS_INVALID_ARGUMENT;
    \\  if (host->abi_version != PROTO_UI_ABI_VERSION)
    \\    return PROTO_UI_STATUS_ABI_MISMATCH;
    \\  if (host->size != PROTO_UI_HOST_V1_LEGACY_SIZE &&
    \\      host->size < PROTO_UI_HOST_V1_SIZE)
    \\    return PROTO_UI_STATUS_ABI_MISMATCH;
    \\  if (host->context == NULL || host->read_generation == NULL ||
    \\      host->read_geometry == NULL)
    \\    return PROTO_UI_STATUS_CALLBACK_MISSING;
    \\  return PROTO_UI_STATUS_SUCCESS;
    \\}
    \\
    \\PROTO_UI_API uint8_t proto_ui_shim_abi_version(void) {
    \\  return PROTO_UI_ABI_VERSION;
    \\}
    \\
    \\PROTO_UI_API uint8_t proto_ui_shim_host_validate(
    \\    const ProtoUiHostV1 *host) {
    \\  return proto_ui_host_validate_v1(host);
    \\}
    \\
    \\PROTO_UI_API uint8_t proto_ui_shim_read_generation(
    \\    const ProtoUiHostV1 *host, uint64_t object_id,
    \\    uint64_t *generation) {
    \\  const uint8_t valid = proto_ui_host_validate_v1(host);
    \\  if (valid != PROTO_UI_STATUS_SUCCESS)
    \\    return valid;
    \\  if (generation == NULL) return PROTO_UI_STATUS_INVALID_ARGUMENT;
    \\  const uint64_t value = host->read_generation(host->context, object_id);
    \\  if (value == 0u) return PROTO_UI_STATUS_CALLBACK_FAILED;
    \\  *generation = value;
    \\  return PROTO_UI_STATUS_SUCCESS;
    \\}
    \\
    \\PROTO_UI_API uint8_t proto_ui_shim_read_geometry(
    \\    const ProtoUiHostV1 *host, uint64_t object_id,
    \\    ProtoUiGeometry *geometry) {
    \\  const uint8_t valid = proto_ui_host_validate_v1(host);
    \\  if (valid != PROTO_UI_STATUS_SUCCESS)
    \\    return valid;
    \\  if (geometry == NULL) return PROTO_UI_STATUS_INVALID_ARGUMENT;
    \\  ProtoUiGeometry value;
    \\  if (host->read_geometry(host->context, object_id, &value) != 1u)
    \\    return PROTO_UI_STATUS_CALLBACK_FAILED;
    \\  *geometry = value;
    \\  return PROTO_UI_STATUS_SUCCESS;
    \\}
    \\
    \\PROTO_UI_API uint8_t proto_ui_shim_read_frame_state(
    \\    const ProtoUiHostV1 *host, uint64_t frame_id,
    \\    ProtoUiFrameState *frame_state) {
    \\  const uint8_t valid = proto_ui_host_validate_v1(host);
    \\  if (valid != PROTO_UI_STATUS_SUCCESS)
    \\    return valid;
    \\  if (frame_state == NULL) return PROTO_UI_STATUS_INVALID_ARGUMENT;
    \\  if (host->size < PROTO_UI_HOST_V1_SIZE ||
    \\      host->read_frame_state == NULL)
    \\    return PROTO_UI_STATUS_FRAME_STATE_UNSUPPORTED;
    \\  ProtoUiFrameState value;
    \\  if (host->read_frame_state(host->context, frame_id, &value) != 1u)
    \\    return PROTO_UI_STATUS_CALLBACK_FAILED;
    \\  *frame_state = value;
    \\  return PROTO_UI_STATUS_SUCCESS;
    \\}
    \\
;

pub fn main(minimal: std.process.Init.Minimal) !void {
    const gpa = std.heap.smp_allocator;
    var io_threaded: std.Io.Threaded = .init(gpa, .{});
    const io = io_threaded.io();
    const cwd = std.Io.Dir.cwd();

    var args = try std.process.Args.Iterator.initAllocator(minimal.args, gpa);
    defer args.deinit();
    _ = args.next();

    const header_path = args.next() orelse return error.MissingHeaderArg;
    const manifest_path = args.next() orelse return error.MissingManifestArg;
    const shim_path = args.next() orelse return error.MissingShimArg;

    try cwd.writeFile(io, .{ .sub_path = header_path, .data = header });

    try cwd.writeFile(io, .{ .sub_path = manifest_path, .data = manifest });
    try cwd.writeFile(io, .{ .sub_path = shim_path, .data = shim });
}
