//! Generates the ABI header and a non-normative ABI summary.  Outputs are
//! build artifacts outside tracked inherited Emacs C source.  The authoritative
//! ownership manifest is `src/proto-ui/adapter.zig`.

const std = @import("std");

const header =
    \\/* Generated by zig build; do not edit. */
    \\#ifndef PROTO_UI_ABI_V1_H
    \\#define PROTO_UI_ABI_V1_H
    \\
    \\#include <stddef.h>
    \\#include <stdint.h>
    \\
    \\#ifdef __cplusplus
    \\extern "C" {
    \\#endif
    \\
    \\#define PROTO_UI_ABI_VERSION 1u
    \\#define PROTO_UI_EUP_MAJOR 1u
    \\#define PROTO_UI_EUP_MINOR 0u
    \\#define PROTO_UI_HOST_V1_SIZE sizeof(ProtoUiHostV1)
    \\
    \\typedef struct ProtoUiGeometry {
    \\  int32_t x;
    \\  int32_t y;
    \\  int32_t width;
    \\  int32_t height;
    \\} ProtoUiGeometry;
    \\
    \\typedef struct ProtoUiHostV1 {
    \\  uint32_t abi_version;
    \\  size_t size;
    \\  void *context;
    \\  uint64_t (*read_generation)(void *context, uint64_t object_id);
    \\  uint8_t (*read_geometry)(void *context, uint64_t object_id,
    \\                           ProtoUiGeometry *geometry);
    \\} ProtoUiHostV1;
    \\
    \\#ifdef __cplusplus
    \\}
    \\#endif
    \\
    \\#endif /* PROTO_UI_ABI_V1_H */
    \\
;

const manifest =
    \\{
    \\  "abi_version": 1,
    \\  "manifest_kind": "abi-summary-non-normative",
    \\  "authoritative_manifest": "src/proto-ui/adapter.zig",
    \\  "eup_major": 1,
    \\  "eup_minor": 0,
    \\  "boundary": "adapter-first",
    \\  "tables": {
    \\    "host_v1": {
    \\      "owner": "emacs-host",
    \\      "callbacks": ["read_generation", "read_geometry"]
    \\    },
    \\    "adapter_v1": {
    \\      "owner": "proto-ui-adapter",
    \\      "callbacks": ["capture_begin", "capture_window", "capture_row", "capture_cursor", "capture_damage", "capture_flush", "capture_cancel"]
    \\    }
    \\  },
    \\  "ownership": {
    \\    "emacs": ["buffers", "frames", "windows", "faces", "fonts", "redisplay"],
    \\    "adapter": ["eup_encoding", "session_state", "damage_policy", "transport"],
    \\    "frontend": ["scene", "input_capture", "renderer", "presentation"]
    \\  }
    \\}
    \\
;

pub fn main(minimal: std.process.Init.Minimal) !void {
    const gpa = std.heap.smp_allocator;
    var io_threaded: std.Io.Threaded = .init(gpa, .{});
    const io = io_threaded.io();
    const cwd = std.Io.Dir.cwd();

    var args = try std.process.Args.Iterator.initAllocator(minimal.args, gpa);
    defer args.deinit();
    _ = args.next();

    const header_path = args.next() orelse return error.MissingHeaderArg;
    const manifest_path = args.next() orelse return error.MissingManifestArg;

    try cwd.writeFile(io, .{ .sub_path = header_path, .data = header });
    try cwd.writeFile(io, .{ .sub_path = manifest_path, .data = manifest });
}
