//! Generated inputs for the C projection of PureRuntimeHostV1.
//! The authoritative ABI remains `src/proto-ui/runtime_host.zig`.

pub const header =
    \\/* Generated by zig build; do not edit. */
    \\#ifndef PROTO_UI_PURE_RUNTIME_HOST_V1_H
    \\#define PROTO_UI_PURE_RUNTIME_HOST_V1_H
    \\
    \\#include <stddef.h>
    \\#include <stdint.h>
    \\#include <stdbool.h>
    \\
    \\#ifdef __cplusplus
    \\extern "C" {
    \\#endif
    \\
    \\#define PROTO_UI_PURE_RUNTIME_HOST_ABI_VERSION 1u
    \\#define PROTO_UI_PURE_RUNTIME_HOST_V1_SIZE sizeof(ProtoUiPureRuntimeHostV1)
    \\
    \\typedef enum ProtoUiPureRuntimeStatus {
    \\  PROTO_UI_RUNTIME_OK = 0,
    \\  PROTO_UI_RUNTIME_INVALID = 1,
    \\  PROTO_UI_RUNTIME_UNSUPPORTED = 2,
    \\  PROTO_UI_RUNTIME_NOT_FOUND = 3,
    \\  PROTO_UI_RUNTIME_BUSY = 4,
    \\  PROTO_UI_RUNTIME_GENERATION_MISMATCH = 5,
    \\  PROTO_UI_RUNTIME_FAILED = 6
    \\} ProtoUiPureRuntimeStatus;
    \\
    \\typedef struct ProtoUiIdentity {
    \\  uint64_t id;
    \\  uint64_t generation;
    \\} ProtoUiIdentity;
    \\
    \\typedef struct ProtoUiGeometry {
    \\  int32_t x;
    \\  int32_t y;
    \\  int32_t width;
    \\  int32_t height;
    \\} ProtoUiGeometry;
    \\
    \\typedef struct ProtoUiFrameState {
    \\  uint64_t generation;
    \\  uint8_t visibility;
    \\  uint8_t focused;
    \\  uint8_t reserved[6];
    \\} ProtoUiFrameState;
    \\
    \\typedef struct ProtoUiTerminalCreateRequest {
    \\  uint64_t requested_generation;
    \\  uint8_t kind;
    \\  uint8_t reserved[7];
    \\} ProtoUiTerminalCreateRequest;
    \\
    \\typedef struct ProtoUiCaptureRequest {
    \\  ProtoUiIdentity frame;
    \\  uint64_t redisplay_generation;
    \\  uint32_t flags;
    \\  uint32_t reserved;
    \\} ProtoUiCaptureRequest;
    \\
    \\typedef struct ProtoUiWindowRecord {
    \\  uint64_t id;
    \\  uint64_t generation;
    \\  int32_t x;
    \\  int32_t y;
    \\  int32_t width;
    \\  int32_t height;
    \\  uint32_t flags;
    \\  uint32_t reserved;
    \\} ProtoUiWindowRecord;
    \\
    \\typedef struct ProtoUiRowRecord {
    \\  uint64_t window_id;
    \\  uint32_t row_index;
    \\  int32_t x;
    \\  int32_t y;
    \\  int32_t width;
    \\  int32_t height;
    \\  int32_t ascent;
    \\  int32_t descent;
    \\  int32_t baseline;
    \\  int32_t visible_height;
    \\  uint32_t flags;
    \\  uint32_t reserved;
    \\} ProtoUiRowRecord;
    \\
    \\typedef struct ProtoUiRunRecord {
    \\  uint64_t run_id;
    \\  uint64_t window_id;
    \\  uint32_t row_index;
    \\  uint32_t face_id;
    \\  uint32_t face_generation;
    \\  uint32_t font_id;
    \\  int32_t x;
    \\  int32_t y;
    \\  int32_t width;
    \\  int32_t height;
    \\  uint8_t direction;
    \\  uint8_t kind;
    \\  uint16_t text_length;
    \\  uint32_t reserved;
    \\  uint8_t text[120];
    \\} ProtoUiRunRecord;
    \\
    \\typedef struct ProtoUiShapedGlyphRecord {
    \\  uint32_t glyph_id;
    \\  uint32_t cluster;
    \\  int16_t x_offset;
    \\  int16_t y_offset;
    \\  uint16_t advance_x;
    \\  uint16_t advance_y;
    \\} ProtoUiShapedGlyphRecord;
    \\
    \\typedef struct ProtoUiShapedRunRecord {
    \\  uint64_t run_id;
    \\  uint64_t window_id;
    \\  uint32_t row_index;
    \\  uint32_t face_id;
    \\  uint32_t face_generation;
    \\  uint32_t font_id;
    \\  uint32_t glyph_count;
    \\  uint16_t direction;
    \\  uint16_t flags;
    \\  uint32_t reserved;
    \\  int32_t x;
    \\  int32_t y;
    \\  int32_t width;
    \\  int32_t height;
    \\  ProtoUiShapedGlyphRecord glyphs[7];
    \\} ProtoUiShapedRunRecord;
    \\
    \\typedef struct ProtoUiCursorRecord {
    \\  uint64_t window_id;
    \\  uint32_t row_index;
    \\  int32_t x;
    \\  int32_t y;
    \\  int32_t width;
    \\  int32_t height;
    \\  uint8_t kind;
    \\  bool visible;
    \\  bool active;
    \\  uint8_t reserved[5];
    \\} ProtoUiCursorRecord;
    \\
    \\typedef struct ProtoUiDamageRecord {
    \\  int32_t x;
    \\  int32_t y;
    \\  int32_t width;
    \\  int32_t height;
    \\  uint8_t reason;
    \\  uint8_t reserved[3];
    \\} ProtoUiDamageRecord;
    \\
    \\typedef struct ProtoUiFaceRecord {
    \\  uint8_t bytes[96];
    \\} ProtoUiFaceRecord;
    \\
    \\typedef struct ProtoUiFontRecord {
    \\  uint8_t bytes[224];
    \\} ProtoUiFontRecord;
    \\
    \\typedef struct ProtoUiImageDefineRecord {
    \\  uint8_t bytes[72];
    \\} ProtoUiImageDefineRecord;
    \\
    \\typedef struct ProtoUiImageFragmentRecord {
    \\  uint32_t image_id;
    \\  uint32_t generation;
    \\  uint16_t fragment_index;
    \\  uint16_t fragment_count;
    \\  uint32_t byte_length;
    \\  uint32_t reserved;
    \\  uint8_t bytes[1024];
    \\} ProtoUiImageFragmentRecord;
    \\
    \\typedef struct ProtoUiInputEvent {
    \\  uint64_t event_id;
    \\  uint64_t frame_id;
    \\  uint16_t kind;
    \\  uint16_t modifiers;
    \\  uint32_t code;
    \\  uint32_t repeat;
    \\  uint16_t payload_length;
    \\  uint16_t reserved;
    \\  uint8_t payload[64];
    \\} ProtoUiInputEvent;
    \\
    \\typedef struct ProtoUiInputAck {
    \\  uint64_t event_id;
    \\  bool accepted;
    \\  ProtoUiPureRuntimeStatus status;
    \\  uint8_t reserved[6];
    \\} ProtoUiInputAck;
    \\
    \\typedef struct ProtoUiInputResult {
    \\  uint64_t event_id;
    \\  uint8_t command_status;
    \\  bool changed_display;
    \\  uint8_t reserved[6];
    \\} ProtoUiInputResult;
    \\
    \\typedef struct ProtoUiCompletionStatus {
    \\  uint64_t transaction_id;
    \\  ProtoUiPureRuntimeStatus status;
    \\  bool completed;
    \\  uint8_t reserved[6];
    \\} ProtoUiCompletionStatus;
    \\
    \\typedef struct ProtoUiHeartbeatResult {
    \\  uint64_t sequence;
    \\  uint32_t pending_work;
    \\  bool healthy;
    \\  uint8_t reserved[3];
    \\} ProtoUiHeartbeatResult;
    \\
    \\typedef struct ProtoUiDiagnosticRecord {
    \\  uint32_t code;
    \\  uint8_t severity;
    \\  uint8_t reserved[3];
    \\  uint16_t message_length;
    \\  uint8_t reserved2[6];
    \\  uint8_t message[120];
    \\} ProtoUiDiagnosticRecord;
    \\
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiTerminalCreateFn)(
    \\  void *context, const ProtoUiTerminalCreateRequest *request,
    \\  ProtoUiIdentity *result);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiIdentityOperationFn)(
    \\  void *context, const ProtoUiIdentity *identity);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiFrameRegisterFn)(
    \\  void *context, const ProtoUiIdentity *host_frame,
    \\  ProtoUiIdentity *protocol_frame);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiFrameStateFn)(
    \\  void *context, const ProtoUiIdentity *frame,
    \\  ProtoUiFrameState *state);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiFrameGeometryFn)(
    \\  void *context, const ProtoUiIdentity *frame,
    \\  ProtoUiGeometry *geometry);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureBeginFn)(
    \\  void *context, const ProtoUiCaptureRequest *request,
    \\  ProtoUiIdentity *session);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureWindowFn)(
    \\  void *context, const ProtoUiIdentity *session,
    \\  const ProtoUiWindowRecord *record);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureRowFn)(
    \\  void *context, const ProtoUiIdentity *session,
    \\  const ProtoUiRowRecord *record);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureRunFn)(
    \\  void *context, const ProtoUiIdentity *session,
    \\  const ProtoUiRunRecord *record);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureShapedRunFn)(
    \\  void *context, const ProtoUiIdentity *session,
    \\  const ProtoUiShapedRunRecord *record);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureCursorFn)(
    \\  void *context, const ProtoUiIdentity *session,
    \\  const ProtoUiCursorRecord *record);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureDamageFn)(
    \\  void *context, const ProtoUiIdentity *session,
    \\  const ProtoUiDamageRecord *record);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureFaceFn)(
    \\  void *context, const ProtoUiIdentity *session,
    \\  const ProtoUiFaceRecord *record);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureFontFn)(
    \\  void *context, const ProtoUiIdentity *session,
    \\  const ProtoUiFontRecord *record);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureImageDefineFn)(
    \\  void *context, const ProtoUiIdentity *session,
    \\  const ProtoUiImageDefineRecord *record);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureImageFragmentFn)(
    \\  void *context, const ProtoUiIdentity *session,
    \\  const ProtoUiImageFragmentRecord *record);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCaptureOperationFn)(
    \\  void *context, const ProtoUiIdentity *session);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiInputDeliverFn)(
    \\  void *context, const ProtoUiInputEvent *event,
    \\  ProtoUiInputAck *ack);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiInputResultFn)(
    \\  void *context, const ProtoUiInputResult *result);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiCompletionFn)(
    \\  void *context, const ProtoUiCompletionStatus *result);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiHeartbeatFn)(
    \\  void *context, ProtoUiHeartbeatResult *result);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiOperationFn)(void *context);
    \\typedef ProtoUiPureRuntimeStatus (*ProtoUiDiagnosticFn)(
    \\  void *context, const ProtoUiDiagnosticRecord *record);
    \\
    \\typedef struct ProtoUiTerminalGroupV1 {
    \\  uint32_t abi_version;
    \\  size_t size;
    \\  void *context;
    \\  ProtoUiTerminalCreateFn create_terminal;
    \\  ProtoUiIdentityOperationFn activate_terminal;
    \\  ProtoUiIdentityOperationFn delete_terminal;
    \\} ProtoUiTerminalGroupV1;
    \\
    \\typedef struct ProtoUiFrameGroupV1 {
    \\  uint32_t abi_version;
    \\  size_t size;
    \\  void *context;
    \\  ProtoUiFrameRegisterFn register_frame;
    \\  ProtoUiIdentityOperationFn unregister_frame;
    \\  ProtoUiFrameStateFn read_frame_state;
    \\  ProtoUiFrameGeometryFn read_geometry;
    \\} ProtoUiFrameGroupV1;
    \\
    \\typedef struct ProtoUiRedisplayGroupV1 {
    \\  uint32_t abi_version;
    \\  size_t size;
    \\  void *context;
    \\  ProtoUiCaptureBeginFn begin_capture;
    \\  ProtoUiCaptureWindowFn observe_window;
    \\  ProtoUiCaptureRowFn observe_row;
    \\  ProtoUiCaptureRunFn observe_run;
    \\  ProtoUiCaptureCursorFn observe_cursor;
    \\  ProtoUiCaptureDamageFn observe_damage;
    \\  ProtoUiCaptureFaceFn observe_face;
    \\  ProtoUiCaptureFontFn observe_font;
    \\  ProtoUiCaptureShapedRunFn observe_shaped_run;
    \\  ProtoUiCaptureImageDefineFn observe_image_define;
    \\  ProtoUiCaptureImageFragmentFn observe_image_fragment;
    \\  ProtoUiCaptureOperationFn commit_capture;
    \\  ProtoUiCaptureOperationFn cancel_capture;
    \\} ProtoUiRedisplayGroupV1;
    \\
    \\_Static_assert(offsetof(ProtoUiRedisplayGroupV1, observe_face) <
    \\              offsetof(ProtoUiRedisplayGroupV1, observe_font),
    \\              "invalid resource callback ordering");
    \\_Static_assert(offsetof(ProtoUiRedisplayGroupV1, observe_image_define) <
    \\              offsetof(ProtoUiRedisplayGroupV1, observe_image_fragment),
    \\              "invalid image callback ordering");
    \\_Static_assert(offsetof(ProtoUiRedisplayGroupV1, observe_run) <
    \\              offsetof(ProtoUiRedisplayGroupV1, observe_shaped_run),
    \\              "invalid shaped callback ordering");
    \\_Static_assert(offsetof(ProtoUiRedisplayGroupV1, observe_font) <
    \\              offsetof(ProtoUiRedisplayGroupV1, observe_shaped_run),
    \\              "invalid shaped callback ordering");
    \\
    \\typedef struct ProtoUiInputGroupV1 {
    \\  uint32_t abi_version;
    \\  size_t size;
    \\  void *context;
    \\  ProtoUiInputDeliverFn deliver_event;
    \\  ProtoUiInputResultFn deliver_result;
    \\  ProtoUiCompletionFn deliver_completion_status;
    \\} ProtoUiInputGroupV1;
    \\
    \\typedef struct ProtoUiLifecycleGroupV1 {
    \\  uint32_t abi_version;
    \\  size_t size;
    \\  void *context;
    \\  ProtoUiHeartbeatFn heartbeat;
    \\  ProtoUiOperationFn flush;
    \\  ProtoUiDiagnosticFn diagnostic;
    \\  ProtoUiOperationFn cancel_all_pending_work;
    \\} ProtoUiLifecycleGroupV1;
    \\
    \\typedef struct ProtoUiPureRuntimeHostV1 {
    \\  uint32_t abi_version;
    \\  size_t size;
    \\  void *context;
    \\  const ProtoUiTerminalGroupV1 *terminal;
    \\  const ProtoUiFrameGroupV1 *frame;
    \\  const ProtoUiRedisplayGroupV1 *redisplay;
    \\  const ProtoUiInputGroupV1 *input;
    \\  const ProtoUiLifecycleGroupV1 *lifecycle;
    \\} ProtoUiPureRuntimeHostV1;
    \\
    \\_Static_assert(sizeof(ProtoUiGeometry) == 16u, "invalid Geometry ABI");
    \\_Static_assert(sizeof(ProtoUiFrameState) == 16u, "invalid FrameState ABI");
    \\_Static_assert(sizeof(ProtoUiIdentity) == 16u, "invalid Identity ABI");
    \\_Static_assert(offsetof(ProtoUiTerminalCreateRequest, kind) == 8u,
    \\              "invalid TerminalCreateRequest ABI");
    \\_Static_assert(offsetof(ProtoUiCaptureRequest, redisplay_generation) == 16u,
    \\              "invalid CaptureRequest ABI");
    \\_Static_assert(offsetof(ProtoUiRunRecord, face_generation) == 24u,
    \\              "invalid RunRecord ABI");
    \\_Static_assert(offsetof(ProtoUiRunRecord, font_id) == 28u,
    \\              "invalid RunRecord ABI");
    \\_Static_assert(offsetof(ProtoUiRunRecord, text) == 56u,
    \\              "invalid RunRecord ABI");
    \\_Static_assert(sizeof(ProtoUiFaceRecord) == 96u,
    \\              "invalid FaceRecord ABI");
    \\_Static_assert(sizeof(ProtoUiFontRecord) == 224u,
    \\              "invalid FontRecord ABI");
    \\_Static_assert(sizeof(ProtoUiImageDefineRecord) == 72u,
    \\              "invalid ImageDefineRecord ABI");
    \\_Static_assert(sizeof(ProtoUiImageFragmentRecord) == 1044u,
    \\              "invalid ImageFragmentRecord ABI");
    \\_Static_assert(sizeof(ProtoUiShapedGlyphRecord) == 16u,
    \\              "invalid ShapedGlyphRecord ABI");
    \\_Static_assert(offsetof(ProtoUiShapedRunRecord, glyphs) == 60u,
    \\              "invalid ShapedRunRecord ABI");
    \\_Static_assert(sizeof(ProtoUiShapedRunRecord) == 176u,
    \\              "invalid ShapedRunRecord ABI");
    \\_Static_assert(sizeof(ProtoUiRunRecord) == 176u,
    \\              "invalid RunRecord ABI");
    \\_Static_assert(offsetof(ProtoUiInputEvent, payload) == 32u,
    \\              "invalid InputEvent ABI");
    \\_Static_assert(sizeof(ProtoUiPureRuntimeHostV1) >= 56u,
    \\              "invalid PureRuntimeHostV1 ABI");
    \\
    \\#ifdef __cplusplus
    \\}
    \\#endif
    \\
    \\#endif /* PROTO_UI_PURE_RUNTIME_HOST_V1_H */
    \\
;

pub const conformance =
    \\/* Generated C ABI conformance for PureRuntimeHostV1; do not edit. */
    \\#include "pure_runtime_host_v1.h"
    \\
    \\static ProtoUiPureRuntimeStatus stub_identity_op(void *context,
    \\    const ProtoUiIdentity *identity) {
    \\  (void)context; (void)identity; return PROTO_UI_RUNTIME_OK;
    \\}
    \\
    \\int proto_ui_pure_runtime_host_abi_conformance(void) {
    \\  ProtoUiTerminalGroupV1 terminal = {1, sizeof(ProtoUiTerminalGroupV1), (void *)&terminal,
    \\    NULL, stub_identity_op, stub_identity_op};
    \\  ProtoUiFrameGroupV1 frame = {1, sizeof(ProtoUiFrameGroupV1), (void *)&frame,
    \\    NULL, stub_identity_op, NULL, NULL};
    \\  ProtoUiRedisplayGroupV1 redisplay = {1, sizeof(ProtoUiRedisplayGroupV1), (void *)&redisplay,
    \\    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};
    \\  ProtoUiInputGroupV1 input = {1, sizeof(ProtoUiInputGroupV1), (void *)&input,
    \\    NULL, NULL, NULL};
    \\  ProtoUiLifecycleGroupV1 lifecycle = {1, sizeof(ProtoUiLifecycleGroupV1), (void *)&lifecycle,
    \\    NULL, NULL, NULL, NULL};
    \\  ProtoUiPureRuntimeHostV1 host = {1, sizeof(host), (void *)&host,
    \\    &terminal, &frame, &redisplay, &input, &lifecycle};
    \\
    \\  if (host.terminal == NULL || host.frame == NULL ||
    \\      host.redisplay == NULL || host.input == NULL || host.lifecycle == NULL)
    \\    return 1;
    \\  if (host.terminal->abi_version != 1u ||
    \\      host.terminal->size != sizeof(ProtoUiTerminalGroupV1))
    \\    return 2;
    \\  if (host.redisplay->begin_capture != NULL ||
    \\      host.lifecycle->heartbeat != NULL)
    \\    return 3;
    \\  return 0;
    \\}
    \\
;

pub const manifest =
    \\{"manifest_version":1,"kind":"proto-ui-pure-runtime-host-abi-c","abi_version":1,"registered":false,"runtime_available":false,"decision_status":"approved","reason_code":"runtime_host_linkage_or_registration_missing","c_conformance":"implemented"}
    \\
;
